# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.20'

    - name: Install Prisma CLI
      run: npm install -g prisma

    - name: Initialize Prisma
      run: npx prisma init

    - name: Generate Prisma Client
      run: npx prisma generate

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
